---
- hosts: all
  remote_user: root
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson

- name: "Setup prerequesities"
  hosts: all
  remote_user: root
  roles:
    - common
  tags: setup-common

- hosts: all
  remote_user: root
  tasks:
    - name: check keys
      debug: msg="{{ hostvars[item] }}"
      with_items: "{{ groups['all'] }}"
      tags:
        - ssh

    - name: "Remove local ip and hostname from /etc/hosts"
      lineinfile:
        path: /etc/hosts
        state: absent
        regexp: '127.0.1.1 {{ hostvars[item].ansible_hostname }} .*'
      with_items: "{{ groups['all'] }}"
      tags:
        - etc_hosts

    - name: Add IP address of all hosts to all hosts
      lineinfile:
        dest: /etc/hosts
        line: "{{ item }} {{ hostvars[item].ansible_hostname }}"
        state: present
      with_items: "{{ groups['all'] }}"
      tags:
        - etc_hosts

    - name: "Create user spark"
      user:
        name: "{{ spark_user }}"
        group: "{{ group_name }}"
        generate_ssh_key: yes

    - name: Set authorized key for user spark copying it from current user
      authorized_key:
        user: "{{ spark_user }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

    - name: "Fetch all public ssh keys"
      shell: cat /home/{{ spark_user }}/.ssh/id_rsa.pub
      register: ssh_keys
      tags:
        - ssh

    - name: check keys
      debug: msg="{{ ssh_keys.stdout }}"
      tags:
        - ssh

    - name: deploy keys on all servers
      authorized_key: user={{ spark_user }} key="{{ item[0] }}"
      delegate_to: "{{ item[1] }}"
      with_nested:
        - "{{ ssh_keys.stdout }}"
        - "{{ groups['spark-common'] }}"
      tags:
        - ssh
  tags:
    - pre-tasks