---
- hosts: hive
  remote_user: root
  gather_facts: no
  pre_tasks:
    - name: "Create user hive"
      user:
        name: "{{ hive_user }}"
        group: "{{ group_name }}"
        generate_ssh_key: yes
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
    - name: "Install python-pkg-resources"
      raw: apt-get install python-pkg-resources
    - name: "Install pip"
      apt:
        name: "python-pip"
    - name: "Install virtualenv"
      apt:
        name: "virtualenv"
    - name: "Install psycopg2"
      pip:
        name: "psycopg2-binary"

- hosts: hive
  remote_user: root
  roles:
    - postgres
  tags:
    - postgres

- hosts: hive
  remote_user: root
  roles:
    - hive
  tags:
    - hive