---
- name: "Create dir for spark-model-selection"
  file:
    path: "{{ spark_model_selection_dir }}"
    owner: "{{ spark_user }}"
    group: "{{ group_name }}"
    mode: "u+rwx,g+rx,o-rwx"
    state: directory
    recurse: yes

- name: "Clone spark-model-selection"
  git:
    repo: "{{ spark_model_selection_repo }}"
    dest: "{{ spark_model_selection_dir }}"
    version: "{{ spark_model_selection_branch }}"

- name: "Build spark-model-selection"
  command: "chdir={{ spark_model_selection_dir }} mvn clean install"